name = "reactfood-app"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
cwd = "."

[build.upload]
format = "directory"
dir = "dist"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200